image: alpine:latest
stages:
  - build
  - review
  - deploy

variables:
  AWS_DEFAULT_REGION: us-east-2
  LIVE_BUCKET_NAME: connorfinnell.com
  TEST_BUCKET_NAME: connorfinnell-com-static-site

build:
  stage: build
  script:
    - mkdir _site/
    - cp index.html _site/
    - cp -r assets/ _site/
    - cp -r images/ _site/
  artifacts:
    paths:
      - _site/

deploy_review:
  stage: review
  image: python:3.6-alpine
  only:
    - review
  before_script:
    - pip install awscli
  script:
    - aws s3 sync _site s3://${TEST_BUCKET_NAME}
  environment:
    name: test
    url: http://${TEST_BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/
    
deploy_live:
  stage: deploy
  image: python:3.6-alpine
  only:
    - master
  before_script:
    - pip install awscli
  script:
    - aws s3 sync _site s3://${LIVE_BUCKET_NAME}
  environment:
    name: live
    url: http://${LIVE_BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/
