baseURL = "https://connorfinnell.com/"
languageCode = "en-us"
title = "Connor Finnell"
theme = "lynx"
enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  favicon = "favicon.ico"
  name = "Connor Finnell"
  headline = "Software &bull; Music &bull; Curiosity"
  image = "https://gravatar.com/avatar/d351ab7da92ecda1d399f158c8b50cd5?s=2048"
  links = [
    { github = "https://github.com/cjfinnell" },
    { keybase = "https://keybase.io/cfin" },
    { linkedin = "https://www.linkedin.com/in/cjfinnell/" },
    { instagram = "https://www.instagram.com/connorfinnell/" },
    { twitter = "https://twitter.com/@thecfin" },
    { email = "mailto:contact@connorfinnell.com" },
    { resume = { href = "/resume.pdf", text = "Resume" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
